generate-git-snapshot: make ADD_TO_VERSION_STRING pass through the DCH loop

diff --git a/scripts/generate-git-snapshot b/scripts/generate-git-snapshot
--- a/scripts/generate-git-snapshot
+++ b/scripts/generate-git-snapshot
@@ -300,24 +300,33 @@ changelog_generation() {
   if [ "${SKIP_DCH:-}" = "true" ] ; then
     echo "*** SKIP_DCH is set, not modifying debian/changelog therefore ***"
   else
-    if [ -n "${tag:-}" ] && [ "${tag:-}" != "none" ] ; then
-      echo "Tag parameter found (and not set to 'none'), not touching the changelog."
-    elif [ "${1:-}" = "identify" ] ; then
-      echo "Trying to identify latest tag / merge..."
+        # if the tag exists and ADD_TAG_TO_VERSION_STRING is true
+        if [ -n "${tag:-}" ] && [ "${tag:-}" != "none" ] && [ -n "${ADD_TAG_TO_VERSION_STRING:-}" ] && [ ${ADD_TAG_TO_VERSION_STRING:-} = "true" ]; then
+            TAG_IN_VERSION_STRING="true"
+        else
+            TAG_IN_VERSION_STRING="false"
+        fi
 
-      if ! git describe $(git rev-list --tags='[^u]*' --max-count=1 HEAD) >/dev/null ; then
-        echo "Failed to identify latest change, falling back to auto mode."
-        git_dch_auto
-      else
-        identify_latest_change
-      fi
-    elif [ -r debian/gbp.conf ] ; then
-      echo "Found debian/gbp.conf, using git-dch with auto mode."
-      git_dch_auto
-    else
-      echo "Using git-dch with auto mode."
-      git_dch_auto
-    fi
+        # if the tag exists and TAG_IN_VERSION_STRING is false, then pass it to dch
+        if [ -n "${tag:-}" ] && [ "${tag:-}" != "none" ] && [ ${TAG_IN_VERSION_STRING} = "false" ]; then
+            echo "Tag parameter found (and not set to 'none'), not touching the changelog."
+        elif [ "${1:-}" = "identify" ] ; then
+            echo "Trying to identify latest tag / merge..."
+
+        if ! git describe $(git rev-list --tags='[^u]*' --max-count=1 HEAD) >/dev/null ; then
+            echo "Failed to identify latest change, falling back to auto mode."
+            git_dch_auto
+        else
+            identify_latest_change
+        fi
+
+        elif [ -r debian/gbp.conf ] ; then
+            echo "Found debian/gbp.conf, using git-dch with auto mode."
+            git_dch_auto
+        else
+            echo "Using git-dch with auto mode."
+            git_dch_auto
+        fi
 
     # get rid of "UNRELEASED" distribution header, only
     # necessary if the debian/changelog was modified
